/**
* Product model representing a store item.
* Using a TypeScript interface provides strong typing
* and improves readability and safety in tests.
*/
export interface Product {
  id?: number;               // Optional because it's generated by the API
  title: string;
  price: number;
  description: string;
  category: string;
  image?: string;
  rating?: {
    rate: number;
    count: number;
  };
}